SET IDENTITY_INSERT dbo.tag ON
Insert into dbo.tag (ID,tagName,tagDescription,tagParentID,tagIsLocked)  Values 
(1, 'Identification Details', 'Identification details for this application.', 43, 'False'), 
(2, 'Gross Annual Income', 'Gross annual incomes belonging to this application.', 250, 'True'), 
(3, 'Language', 'Language', 44, 'True'), 
(4, 'Disability', 'Application data details surrounding disability.', 256, 'True'), 
(5, 'Education Details', 'Education Indicators.', 43, 'False'), 
(6, 'Eligibility Update', 'A distinct eligibility status update details.', 38, 'False'), 
(7, 'Case Note', 'Distinct note related to this application.', 242, 'False'), 
(8, 'Contact Person', 'Application Data related to a specific contact person.', 242, 'False'), 
(9, 'Pregnancy', 'Pregnancy in this household.', 242, 'False'), 
(10, 'Utility Debt', 'Application data related to Utility Debt.', 242, 'False'), 
(11, 'Entrance Offer', 'Applicant offered admission into program.', 38, 'False'), 
(12, 'HUD Homeless', 'HUD homeless housing tag.', 242, 'False'), 
(13, 'Undocumented', 'Undocumented identification tag.', 242, 'False'), 
(14, 'Submission Method', 'Submission method identfication tag.', 242, 'False'), 
(15, 'Check In', 'A distinct check in update this application.', 43, 'False'), 
(16, 'Attachment URL', 'A distinct attachment in this application.', 242, 'False'), 
(17, 'Property Preference', 'Property preference identification tag.', 242, 'False'), 
(18, 'Waitlist', 'Application is approved for waitlist.', 35, 'False'), 
(19, 'NMI', 'Need more information for this application.', 35, 'False'), 
(20, 'Denied', 'Application is denied from program.', 35, 'False'), 
(21, 'THP', 'Transitional Housing Program', 34, 'True'), 
(22, 'SPC', 'Shelter Plus Care', 34, 'True'), 
(23, 'COA', 'City of Austin Program', 34, 'True'), 
(24, 'PIR', 'Parenting in Recovery Program', 34, 'True'), 
(25, 'HF', 'Housing First Program', 34, 'True'), 
(26, 'SR', 'Sierra Ridge', 33, 'True'), 
(27, 'SV', 'Sierra Vista', 33, 'True'), 
(28, 'CR', 'Crossroads', 33, 'True'), 
(29, 'DF', 'Daffodil', 33, 'True'), 
(30, 'VC', 'Vintage Creek', 33, 'True'), 
(31, 'MS', 'M-Station', 33, 'True'), 
(33, 'Property', 'Set of Housing Property options available in this system.', 44, 'True'), 
(34, 'Program', 'Set of Program options available in this system.', 44, 'True'), 
(35, 'Eligibility Status', 'Set of eligibility status options available in this system.', 6, 'False'), 
(36, 'Income Record', 'Incomes related to this application.', 250, 'True'), 
(38, 'Outcome Details', 'Ultimate application outcome.', 242, 'False'), 
(43, 'Application Details', 'Collection of application information included in this system.', 242, 'False'), 
(44, 'System Lookup', 'Collection of lookup options included in this system.', 45, 'True'), 
(45, 'Waitlist Root', 'Distinct waitlist deployment. Should never have details associated with this tag.',,'False'),
(46, 'Texas Gas Services', 'Utility debt source option available in this system.', 10, 'True'), 
(47, 'Austin Energy', 'Utility debt source option available in this system.', 10, 'True'), 
(48, 'Due Date', 'Pregnancy due date tag.', 9, 'True'), 
(49, 'Geo Preference', 'Geographical area preference identification tag.', 43, 'True'), 
(50, 'YTD', 'Year to Date Gross Annual Income', 299, 'False'), 
(51, 'AVG', 'Average Gross Annual Income', 299, 'False'), 
(52, 'OVT', 'Gross Annual Overtime Income', 299, 'False'), 
(53, 'Income Recipient', 'Income Recipient', 250, 'True'), 
(54, 'Employment Start Date', 'Employment Start Date', 271, 'False'), 
(55, 'Special Housing Needs', 'Disability requires special housing needs.', 4, 'True'), 
(56, 'Household Size', 'Total number of persons in household.', 242, 'False'), 
(57, 'Full Name', 'Contact Full Name', 8, 'True'), 
(58, 'Email', 'Contact Email Address', 8, 'True'), 
(59, 'Phone', 'Contact Phone Number', 8, 'True'), 
(60, 'Relationship Type', 'Contact Relationship to application.', 8, 'True'), 
(61, 'HOH', 'Head of Household', 60, 'True'), 
(62, 'CM', 'Case Manager', 60, 'True'), 
(67, 'Accepted Offer', 'Entrance Offer Accepted', 11, 'False'), 
(70, '60 Day Auto Denial', 'Automatic Denial after 60 days of inactivity', 35, 'False'), 
(72, 'Rejected Offer', 'Outcome option available in this system.', 11, 'False'), 
(73, 'Legal Details', 'Legal indicators (criminal history).', 43, 'False'), 
(75, 'Abkhazian', 'ab', 3, 'True'), 
(76, 'Afar', 'aa', 3, 'True'), 
(77, 'Afrikaans', 'af', 3, 'True'), 
(78, 'Albanian', 'sq', 3, 'True'), 
(79, 'Amharic', 'am', 3, 'True'), 
(80, 'Arabic', 'ar', 3, 'True'), 
(81, 'Aragonese', 'an', 3, 'True'), 
(82, 'Armenian', 'hy', 3, 'True'), 
(83, 'Assamese', 'as', 3, 'True'), 
(84, 'Aymara', 'ay', 3, 'True'), 
(85, 'Azerbaijani', 'az', 3, 'True'), 
(86, 'Bashkir', 'ba', 3, 'True'), 
(87, 'Basque', 'eu', 3, 'True'), 
(88, 'Bengali (Bangla)', 'bn', 3, 'True'), 
(89, 'Bhutani', 'dz', 3, 'True'), 
(90, 'Bihari', 'bh', 3, 'True'), 
(91, 'Bislama', 'bi', 3, 'True'), 
(92, 'Breton', 'br', 3, 'True'), 
(93, 'Bulgarian', 'bg', 3, 'True'), 
(94, 'Burmese', 'my', 3, 'True'), 
(95, 'Byelorussian (Belarusian)', 'be', 3, 'True'), 
(96, 'Cambodian', 'km', 3, 'True'), 
(97, 'Catalan', 'ca', 3, 'True'), 
(98, 'Cherokee', 3, 'True'), 
(99, 'Chewa', 3, 'True'), 
(100, 'Chinese', 'zh', 3, 'True'), 
(101, 'Chinese (Simplified)', 'zh-Hans', 3, 'True'), 
(102, 'Chinese (Traditional)', 'zh-Hant', 3, 'True'), 
(103, 'Corsican', 'co', 3, 'True'), 
(104, 'Croatian', 'hr', 3, 'True'), 
(105, 'Czech', 'cs', 3, 'True'), 
(106, 'Danish', 'da', 3, 'True'), 
(107, 'Divehi', 3, 'True'), 
(108, 'Dutch', 'nl', 3, 'True'), 
(109, 'Edo', 3, 'True'), 
(110, 'English', 'en', 3, 'True'), 
(111, 'Esperanto', 'eo', 3, 'True'), 
(112, 'Estonian', 'et', 3, 'True'), 
(113, 'Faeroese', 'fo', 3, 'True'), 
(114, 'Farsi', 'fa', 3, 'True'), 
(115, 'Fiji', 'fj', 3, 'True'), 
(116, 'Finnish', 'fi', 3, 'True'), 
(117, 'Flemish', 3, 'True'), 
(118, 'French', 'fr', 3, 'True'), 
(119, 'Frisian', 'fy', 3, 'True'), 
(120, 'Fulfulde', 3, 'True'), 
(121, 'Galician', 'gl', 3, 'True'), 
(122, 'Gaelic (Scottish)', 'gd', 3, 'True'), 
(123, 'Gaelic (Manx)', 'gv', 3, 'True'), 
(124, 'Georgian', 'ka', 3, 'True'), 
(125, 'German', 'de', 3, 'True'), 
(126, 'Greek', 'el', 3, 'True'), 
(127, 'Greenlandic', 'kl', 3, 'True'), 
(128, 'Guarani', 'gn', 3, 'True'), 
(129, 'Gujarati', 'gu', 3, 'True'), 
(130, 'Haitian Creole', 'ht', 3, 'True'), 
(131, 'Hausa', 'ha', 3, 'True'), 
(132, 'Hawaiian', 3, 'True'), 
(133, 'Hebrew', 'he', 3, 'True'), 
(134, 'Hindi', 'hi', 3, 'True'), 
(135, 'Hungarian', 'hu', 3, 'True'), 
(136, 'Ibibio', 3, 'True'), 
(137, 'Icelandic', 'is', 3, 'True'), 
(138, 'Ido', 'io', 3, 'True'), 
(139, 'Igbo', 3, 'True'), 
(140, 'Indonesian', 'id', 3, 'True'), 
(141, 'Interlingua', 'ia', 3, 'True'), 
(142, 'Interlingue', 'ie', 3, 'True'), 
(143, 'Inuktitut', 'iu', 3, 'True'), 
(144, 'Inupiak', 'ik', 3, 'True'), 
(145, 'Irish', 'ga', 3, 'True'), 
(146, 'Italian', 'it', 3, 'True'), 
(147, 'Japanese', 'ja', 3, 'True'), 
(148, 'Javanese', 'jv', 3, 'True'), 
(149, 'Kannada', 'kn', 3, 'True'), 
(150, 'Kanuri', 3, 'True'), 
(151, 'Kashmiri', 'ks', 3, 'True'), 
(152, 'Kazakh', 'kk', 3, 'True'), 
(153, 'Kinyarwanda (Ruanda)', 'rw', 3, 'True'), 
(154, 'Kirghiz', 'ky', 3, 'True'), 
(155, 'Kirundi (Rundi)', 'rn', 3, 'True'), 
(156, 'Konkani', 3, 'True'), 
(157, 'Korean', 'ko', 3, 'True'), 
(158, 'Kurdish', 'ku', 3, 'True'), 
(159, 'Laothian', 'lo', 3, 'True'), 
(160, 'Latin', 'la', 3, 'True'), 
(161, 'Latvian (Lettish)', 'lv', 3, 'True'), 
(162, 'Limburgish ( Limburger)', 'li', 3, 'True'), 
(163, 'Lingala', 'ln', 3, 'True'), 
(164, 'Lithuanian', 'lt', 3, 'True'), 
(165, 'Macedonian', 'mk', 3, 'True'), 
(166, 'Malagasy', 'mg', 3, 'True'), 
(167, 'Malay', 'ms', 3, 'True'), 
(168, 'Malayalam', 'ml', 3, 'True'), 
(169, 'Maltese', 'mt', 3, 'True'), 
(170, 'Maori', 'mi', 3, 'True'), 
(171, 'Marathi', 'mr', 3, 'True'), 
(172, 'Moldavian', 'mo', 3, 'True'), 
(173, 'Mongolian', 'mn', 3, 'True'), 
(174, 'Nauru', 'na', 3, 'True'), 
(175, 'Nepali', 'ne', 3, 'True'), 
(176, 'Norwegian', 'no', 3, 'True'), 
(177, 'Occitan', 'oc', 3, 'True'), 
(178, 'Oriya', 'or', 3, 'True'), 
(179, 'Oromo (Afaan Oromo)', 'om', 3, 'True'), 
(180, 'Papiamentu', 3, 'True'), 
(181, 'Pashto (Pushto)', 'ps', 3, 'True'), 
(182, 'Polish', 'pl', 3, 'True'), 
(183, 'Portuguese', 'pt', 3, 'True'), 
(184, 'Punjabi', 'pa', 3, 'True'), 
(185, 'Quechua', 'qu', 3, 'True'), 
(186, 'Rhaeto-Romance', 'rm', 3, 'True'), 
(187, 'Romanian', 'ro', 3, 'True'), 
(188, 'Russian', 'ru', 3, 'True'), 
(189, 'Sami (Lappish)', 3, 'True'), 
(190, 'Samoan', 'sm', 3, 'True'), 
(191, 'Sangro', 'sg', 3, 'True'), 
(192, 'Sanskrit', 'sa', 3, 'True'), 
(193, 'Serbian', 'sr', 3, 'True'), 
(194, 'Serbo-Croatian', 'sh', 3, 'True'), 
(195, 'Sesotho', 'st', 3, 'True'), 
(196, 'Setswana', 'tn', 3, 'True'), 
(197, 'Shona', 'sn', 3, 'True'), 
(198, 'Sichuan Yi', 'ii', 3, 'True'), 
(199, 'Sindhi', 'sd', 3, 'True'), 
(200, 'Sinhalese', 'si', 3, 'True'), 
(201, 'Siswati', 'ss', 3, 'True'), 
(202, 'Slovak', 'sk', 3, 'True'), 
(203, 'Slovenian', 'sl', 3, 'True'), 
(204, 'Somali', 'so', 3, 'True'), 
(205, 'Spanish', 'es', 3, 'True'), 
(206, 'Sundanese', 'su', 3, 'True'), 
(207, 'Swahili (Kiswahili)', 'sw', 3, 'True'), 
(208, 'Swedish', 'sv', 3, 'True'), 
(209, 'Syriac', 3, 'True'), 
(210, 'Tagalog', 'tl', 3, 'True'), 
(211, 'Tajik', 'tg', 3, 'True'), 
(212, 'Tamazight', 3, 'True'), 
(213, 'Tamil', 'ta', 3, 'True'), 
(214, 'Tatar', 'tt', 3, 'True'), 
(215, 'Telugu', 'te', 3, 'True'), 
(216, 'Thai', 'th', 3, 'True'), 
(217, 'Tibetan', 'bo', 3, 'True'), 
(218, 'Tigrinya', 'ti', 3, 'True'), 
(219, 'Tonga', 'to', 3, 'True'), 
(220, 'Tsonga', 'ts', 3, 'True'), 
(221, 'Turkish', 'tr', 3, 'True'), 
(222, 'Turkmen', 'tk', 3, 'True'), 
(223, 'Twi', 'tw', 3, 'True'), 
(224, 'Uighur', 'ug', 3, 'True'), 
(225, 'Ukrainian', 'uk', 3, 'True'), 
(226, 'Urdu', 'ur', 3, 'True'), 
(227, 'Uzbek', 'uz', 3, 'True'), 
(228, 'Venda', 3, 'True'), 
(229, 'Vietnamese', 'vi', 3, 'True'), 
(230, 'Volapk', 'vo', 3, 'True'), 
(231, 'Wallon', 'wa', 3, 'True'), 
(232, 'Welsh', 'cy', 3, 'True'), 
(233, 'Wolof', 'wo', 3, 'True'), 
(234, 'Xhosa', 'xh', 3, 'True'), 
(235, 'Yi', 3, 'True'), 
(236, 'Yiddish', 'yi', 3, 'True'), 
(237, 'Yoruba', 'yo', 3, 'True'), 
(238, 'Zulu', 'zu', 3, 'True'), 
(242, 'Application Data', 'data details related to this application record.', 45, 'False'), 
(244, 'Submission Details', 'Application Submission', 43, 'False'), 
(246, 'Submission Date', 'Date application was submitted.', 43, 'False'), 
(247, 'Family Details', 'application data elements related to the family in this household', 43, 'False'), 
(248, 'HOH Enrolled', 'Head of Household enrolled in education program.', 5, 'False'), 
(249, 'Program Eligibility', 'Data indicating the eligibility of this application per program.', 6, 'False'), 
(250, 'Income Details', 'Gross Annual Income', 242, 'False'), 
(251, 'Pending', 'Outcome is currently pending.', 35, 'False'), 
(252, 'Criminal History', 'Criminal history legal data.', 73, 'False'), 
(254, 'Entered Program', 'Entrance Offer Accepted - Moved In', 38, 'False'), 
(255, 'Relation', 'Contact Relationship', 8, 'False'), 
(256, 'Health Details', 'Health related data collection.', 242, 'False'), 
(257, 'History of substance use', 'Chronic Substance Use', 4, 'False'), 
(258, 'Debt Source', 'Utility Debt Sources', 10, 'False'), 
(259, 'Amount Owed', 'Amount owed to utility company.', 10, 'False'), 
(260, 'DV History', 'History of Domestic Violence / Sexual Assault', 256, 'False'), 
(261, 'Communicable Disease', 'Communicable disease.', 4, 'False'), 
(263, 'Income Amount', 'Amount of Income Recieved', 250, 'False'), 
(265, 'Income Type', 'Identifys whether this record is employment income or non-employment income.', 250, 'False'), 
(268, 'Language Preference', 'Applicants preferred Language', 242, 'False'), 
(269, 'Interpreter', 'Applicant has interpreter', 268, 'False'), 
(270, 'Nonemployment Income', 'Income is received through non-employment.', 36, 'False'), 
(271, 'Employment Income', 'Income received through employment.', 36, 'False'), 
(272, 'Child Support', 'Income through child support', 270, 'False'), 
(273, 'SSDI', 'Income through disability benefits', 270, 'False'), 
(274, 'SSI', 'Income through public benefits', 270, 'False'), 
(275, 'TANF', 'Income through TANF', 270, 'False'), 
(276, 'Unemployment', 'Income recieved through unemployment benefits', 270, 'False'), 
(277, 'Extra Details', 'Extra information related to this application', 242, 'False'), 
(278, 'Success Project', 'Applicant is part of success project program.', 277, 'False'), 
(279, 'Refugee Resettlement', 'Applicant is part of refugee resettlement program.', 277, 'False'), 
(280, 'Application Name', 'Name used to identify this application', 43, 'False'), 
(282, 'Previous Housing', 242, 'False'), 
(283, 'Aunt Bertha', 'Application submitted through AuntBertha.com', 14, 'False'), 
(284, 'Moved In', 'Moved In', 254, 'False'), 
(285, 'Exited Program', 'Exited Program', 38, 'False'), 
(286, 'Mission', 'This message is display at the top of your application programs mission', 287, 'False'), 
(287, 'System Settings', 'System details', 45, 'False'), 
(288, 'Moved Out', 'Particpant moved out of the property.', 254, 'False'), 
(289, 'Property Address', 'Address for this property location.', 33, 'False'), 
(290, 'Property Phone', 'Leasing office phone number.', 33, 'False'), 
(291, 'Property Fax', 'Leasing office fax number.', 33, 'False'), 
(292, 'Unit Key', 'Unit existing in this property.', 33, 'False'), 
(293, 'Unit Type', 'Bedroom / Bath Size', 292, 'False'), 
(294, 'Unit Number', 'Unit Number.', 292, 'False'), 
(295, 'Unit Address', 'Unit Address.', 292, 'False'), 
(296, 'Unit Building', 'Unit building number.', 292, 'False'), 
(297, 'Unit Sq Ft.', 'Square feet of this unit.', 292, 'False'), 
(298, 'Income Source', 271, 'True'), 
(299, 'Employment Income Measure', 'Type of measurement for this employment income.', 271, 'False'), 
(300, 'Data Type', 'List of data types.', 45, 'False'), 
(301, 'YesNo', 'YesNo data type.', 300, 'False'), 
(302, 'Currency', 'Currency data type.', 300, 'False'), 
(303, 'Date', 'Date data type.', 300, 'False'), 
(304, 'DateWithTime', 'DateWithTime data type.', 300, 'False'), 
(305, 'Float', 'Float data type.', 300, 'False'), 
(306, 'Integer', 'Integer data type.', 300, 'False'), 
(307, 'LongText', 'LongText data type.', 300, 'False'), 
(308, 'ShortText', 'ShortText data type.', 300, 'False'), 
(309, 'Text', 'Text data type.', 300, 'False'), 
(310, 'Time', 'Time data type.', 300, 'False')
(1298,'Utility Company','List of local utility providers.',44,'False'),
(1299,'Utilities','System level details describe particulars of this specific waitlist details including what programs are available at what properties. Variables defining system level details are held in this container.',45,'True'),
(1300,'External Program','External programs applicants may have participatory relationships with.',1310,'False'),
(1301,'Submission Source','Application submission sources beyond paper app.',44,'False'),
(1302,'Disability Type','Types of disabilities.',44,'True'),
(1303,'Possible Outcomes','Outcome options available in this system.',44,'True'),
(1304,'Content Type','Type of content related to a specific detail.',44,'True'),
(1305,'Transaction','Examples of transactional content include meetings',' appointments and purchases. Transactions are a type of structured content.',1304,'True'),
(1306,'Analysis','Examples of analytical content include client reports',' outcome analyses and case management assessments.  Analyzed content is a form of unstructured content.',1304,'True'),
(1307,'Authored','Examples of authored content include text documents',' presentations',' emails',' and case 'False'tes. Authored content is a type of unstructured content.',1304,'True'),
(1308,'Publication','Examples of published content include websites',' handbooks and forms. Published content is a type of unstructured content.',1304,'True'),
(1309,'Aggregate','Aggregate data type.',300,'True'),
(1310,'System Details','Define information related to this specific instance of the Waitlist system. System level details describe particulars including available programs and properties.',45,'True'),
(1312,'Calculation','Calculated field.',300,'True'),
(1313,'Paper App','Application submitted via handwritten paper application.',1301,'False'),
(1314,'SharePoint','Application is submitted via SharePoint interface.',1301,'False'),
(1315,'List','List of items,300,'True'),
(1316,'Related Details Set','Set of related details create the components of this piece of information.',300,'True'),
(1317,'Parent','Parent or grandparent.',60,'False')
