SET IDENTITY_INSERT dbo.tag ON
Insert into dbo.tag (ID,tagName,tagDescription,tagParentID,tagIsLocked,dataType,formatType,tagDateCaption)  Values 
(2,'Gross Annual Income','Gross annual income calculation related to this application.',1327,'True','Calculation',,),
(3,'Languages','Language',44,'True','ShortText',,'Date Recorded'),
(4,'Disability','Application data details surrounding disability.',256,'True','ShortText',,'Date Recorded'),
(5,'Education Details','Education Indicators.',43,'True','Aggregate',,'Date Recorded'),
(6,'Eligibility Update','A distinct eligibility status update details.',38,'True','Transaction',,'Update Date'),
(7,'Case Note','Distinct note related to this application.',43,'True','Text',,'Note Date'),
(8,'Contact Person','Application Data related to a specific contact person.',43,'True','Related Set',,),
(9,'Pregnancy','Pregnancy in this household.',43,'True','ShortText',,),
(10,'Utility Debt','Application data related to Utility Debt.',43,'True','Related Set',,),
(11,'Entered Programs','Applicant offered admission into program.',1303,'True','Transaction',,'Entrance Date'),
(12,'HUD Homeless','Indicating HUD homeless classification.',43,'True','Text',,),
(13,'Undocumented','Undocumented identification tag.',43,'True','Text',,),
(14,'Submission Method','Submission method identfication tag.',244,'True','List',,),
(15,'Check In','A distinct check in update this application.',43,'True','Text',,),
(16,'Attachment URL','A distinct attachment in this application.',43,'True','Text',,),
(17,'Property Preference','Property preference identification tag.',43,'True','Text',,),
(18,'Waitlist','Application is approved for waitlist.',35,'True','List',,),
(19,'NMI','Need more information for this application.',35,'True','List',,),
(20,'Denied','Application is denied from program.',35,'True','List',,),
(21,'SHP','Supportive Housing Program',34,'True','Text',,),
(22,'SPC','Shelter Plus Care',34,'False','Text',,),
(23,'COA','City of Austin Program',34,'False',,','),
(24,'PIR','Parenting in Recovery Program',34,'False',,','),
(25,'HF','Housing First Program',34,'False',,','),
(26,'SR','Sierra Ridge',33,'False',,','),
(27,'SV','Sierra Vista',33,'False',,','),
(28,'CR','Crossroads',33,'False',,','),
(29,'DF','Daffodil',33,'False',,','),
(30,'VC','Vintage Creek',33,'False',,','),
(31,'MS','M-Station',33,'False',,','),
(33,'Property','Set of Housing Property options available in this system.',44,'True','ShortText',,),
(34,'Program','Set of Program options available in this system.',44,'True','ShortText',,),
(35,'Eligibility Status','Set of eligibility status options available in this system.',44,'True','ShortText',,),
(38,'Outcome Details','Ultimate application outcome.',43,'True','Aggregate',,),
(43,'Application Details','Details related to a distinct application submission in this system.',242,'True','List',,),
(44,'Lookups','Collection of all lookup options in this waitlist deployment.',1299,'True',,','),
(45,'Waitlist Root','Distinct waitlist deployment.  This tag will never have details associated with this tag.',,'True',,','),
(46,'Texas Gas Services','Utility debt record with Texas Gas Services.',1298,'False','Currency',,),
(47,'Austin Energy','Utility debt record withy Austin Energy.',1298,'True','Currency',,),
(48,'Due Date','Pregnancy due date tag.',9,'True','Date',,),
(49,'Geo Preference','Geographical area preference identification tag.',43,'True','Text',,),
(50,'YTD Employment','Year to Date Gross Annual Income',271,'True','Currency',,),
(51,'AVG Employment','Average Gross Annual Income. Date is valid employment start date.',271,'True','Currency',,),
(52,'OVT Employment','Gross Annual Overtime Income',271,'True','Currency',,),
(55,'Special Housing Needs','Disability requires special housing needs.',1302,'True','ShortText',,),
(56,'Household Size','Total number of persons in household.',43,'True','Integer',,),
(57,'Full Name','Contact Full Name',8,'True','ShortText',,),
(58,'Email','Contact Email Address',8,'True','ShortText',,),
(59,'Phone','Contact Phone Number',8,'True','ShortText',,),
(60,'Contact Type','Specifies the relation of the contact person for this contact record (Head of Household, Case Manager, Parent)',44,'True','ShortText',,),
(61,'HOH','Head of Household',60,'True','ShortText',,),
(62,'CM','Case Manager',60,'True','ShortText',,),
(67,'Accepted Offer','Entrance Offer Accepted',11,'True',,','),
(70,'Auto Denial After 60+ Inactive Days','Automatic applicant denial after this much time with absolute inactivity.  Absolute inactivity means no check-ins from applicant, no details updated for this application after x number of days.',35,'True','Integer',,),
(72,'Rejected Offer','Outcome option available in this system.',11,'True',,','),
(75,'Abkhazian','Speaks Abkhazian',3,'False',,','),
(76,'Afar','Speaks Afar',3,'False',,','),
(77,'Afrikaans','Speaks Afrikaans',3,'False','ShortText',,),
(78,'Albanian','Speaks Albanian',3,'False','ShortText',,),
(79,'Amharic','Speaks Amharic',3,'False','ShortText',,),
(80,'Arabic','Speaks Arabic',3,'False','ShortText',,),
(81,'Aragonese','Speaks Aragonese',3,'False','ShortText',,),
(82,'Armenian','Speaks Armenian',3,'False','ShortText',,),
(83,'Assamese','Speaks Assamese',3,'False','ShortText',,),
(84,'Aymara','Speaks Aymara',3,'False','ShortText',,),
(85,'Azerbaijani','Speaks Azerbaijani',3,'False','ShortText',,),
(86,'Bashkir','Speaks Bashkir',3,'False','ShortText',,),
(87,'Basque','Speaks Basque',3,'False','ShortText',,),
(88,'Bengali (Bangla)','Speaks Bengali (Bangla)',3,'False','ShortText',,),
(89,'Bhutani','Speaks Bhutani',3,'False','ShortText',,),
(90,'Bihari','Speaks Bihari',3,'False','ShortText',,),
(91,'Bislama','Speaks Bislama',3,'False','ShortText',,),
(92,'Breton','Speaks Breton',3,'False','ShortText',,),
(93,'Bulgarian','Speaks Bulgarian',3,'False','ShortText',,),
(94,'Burmese','Speaks Burmese',3,'False','ShortText',,),
(95,'Byelorussian (Belarusian)','Speaks Byelorussian (Belarusian)',3,'False','ShortText',,),
(96,'Cambodian','Speaks Cambodian',3,'False','ShortText',,),
(97,'Catalan','Speaks Catalan',3,'False','ShortText',,),
(98,'Cherokee','Speaks Cherokee',3,'False','ShortText',,),
(99,'Chewa','Speaks Chewa',3,'False','ShortText',,),
(100,'Chinese','Speaks Chinese',3,'False','ShortText',,),
(101,'Chinese (Simplified)','Speaks Chinese (Simplified)',3,'False','ShortText',,),
(102,'Chinese (Traditional)','Speaks Chinese (Traditional)',3,'False','ShortText',,),
(103,'Corsican','Speaks Corsican',3,'False','ShortText',,),
(104,'Croatian','Speaks Croatian',3,'False','ShortText',,),
(105,'Czech','Speaks Czech',3,'False','ShortText',,),
(106,'Danish','Speaks Danish',3,'False','ShortText',,),
(107,'Divehi','Speaks Divehi',3,'False','ShortText',,),
(108,'Dutch','Speaks Dutch',3,'False','ShortText',,),
(109,'Edo','Speaks Edo',3,'False','ShortText',,),
(110,'English','Speaks English',3,'False','ShortText',,),
(111,'Esperanto','Speaks Esperanto',3,'False','ShortText',,),
(112,'Estonian','Speaks Estonian',3,'False','ShortText',,),
(113,'Faeroese','Speaks Faeroese',3,'False','ShortText',,),
(114,'Farsi','Speaks Farsi',3,'False','ShortText',,),
(115,'Fiji','Speaks Fiji',3,'False','ShortText',,),
(116,'Finnish','Speaks Finnish',3,'False','ShortText',,),
(117,'Flemish','Speaks Flemish',3,'False','ShortText',,),
(118,'French','Speaks French',3,'False','ShortText',,),
(119,'Frisian','Speaks Frisian',3,'False','ShortText',,),
(120,'Fulfulde','Speaks Fulfulde',3,'False','ShortText',,),
(121,'Galician','Speaks Gaelic (Manx)',3,'False','ShortText',,),
(122,'Gaelic (Scottish)','Speaks Gaelic (Scottish)',3,'False','ShortText',,),
(123,'Gaelic (Manx)','Speaks Galician',3,'False','ShortText',,),
(124,'Georgian','Speaks Georgian',3,'False','ShortText',,),
(125,'German','Speaks German',3,'False','ShortText',,),
(126,'Greek','Speaks Greek',3,'False','ShortText',,),
(127,'Greenlandic','Speaks Greenlandic',3,'False','ShortText',,),
(128,'Guarani','Speaks Guarani',3,'False','ShortText',,),
(129,'Gujarati','Speaks Gujarati',3,'False','ShortText',,),
(130,'Haitian Creole','Speaks Haitian Creole',3,'False','ShortText',,),
(131,'Hausa','Speaks Hausa',3,'False','ShortText',,),
(132,'Hawaiian','Speaks Hawaiian',3,'False','ShortText',,),
(133,'Hebrew','Speaks Hebrew',3,'False','ShortText',,),
(134,'Hindi','Speaks Hindi',3,'False','ShortText',,),
(135,'Hungarian','Speaks Hungarian',3,'False','ShortText',,),
(136,'Ibibio','Speaks Ibibio',3,'False','ShortText',,),
(137,'Icelandic','Speaks Icelandic',3,'False','ShortText',,),
(138,'Ido','Speaks Ido',3,'False','ShortText',,),
(139,'Igbo','Speaks Igbo',3,'False','ShortText',,),
(140,'Indonesian','Speaks Indonesian',3,'False','ShortText',,),
(141,'Interlingua','Speaks Interlingua',3,'False','ShortText',,),
(142,'Interlingue','Speaks Interlingue',3,'False','ShortText',,),
(143,'Inuktitut','Speaks Inuktitut',3,'False','ShortText',,),
(144,'Inupiak','Speaks Inupiak',3,'False','ShortText',,),
(145,'Irish','Speaks Irish',3,'False','ShortText',,),
(146,'Italian','Speaks Italian',3,'False','ShortText',,),
(147,'Japanese','Speaks Japanese',3,'False','ShortText',,),
(148,'Javanese','Speaks Javanese',3,'False','ShortText',,),
(149,'Kannada','Speaks Kannada',3,'False','ShortText',,),
(150,'Kanuri','Speaks Kanuri',3,'False','ShortText',,),
(151,'Kashmiri','Speaks Kashmiri',3,'False','ShortText',,),
(152,'Kazakh','Speaks Kazakh',3,'False','ShortText',,),
(153,'Kinyarwanda (Ruanda)','Speaks Kinyarwanda (Ruanda)',3,'False','ShortText',,),
(154,'Kirghiz','Speaks Kirghiz',3,'False','ShortText',,),
(155,'Kirundi (Rundi)','Speaks Kirundi (Rundi)',3,'False','ShortText',,),
(156,'Konkani','Speaks Konkani',3,'False','ShortText',,),
(157,'Korean','Speaks Korean',3,'False','ShortText',,),
(158,'Kurdish','Speaks Kurdish',3,'False','ShortText',,),
(159,'Laothian','Speaks Laothian',3,'False','ShortText',,),
(160,'Latin','Speaks Latin',3,'False','ShortText',,),
(161,'Latvian (Lettish)','Speaks Latvian (Lettish)',3,'False','ShortText',,),
(162,'Limburgish ( Limburger)','Speaks Limburgish ( Limburger)',3,'False','ShortText',,),
(163,'Lingala','Speaks Lingala',3,'False','ShortText',,),
(164,'Lithuanian','Speaks Lithuanian',3,'False','ShortText',,),
(165,'Macedonian','Speaks Macedonian',3,'False','ShortText',,),
(166,'Malagasy','Speaks Malagasy',3,'False','ShortText',,),
(167,'Malay','Speaks Malay',3,'False','ShortText',,),
(168,'Malayalam','Speaks Malayalam',3,'False','ShortText',,),
(169,'Maltese','Speaks Maltese',3,'False','ShortText',,),
(170,'Maori','Speaks Maori',3,'False','ShortText',,),
(171,'Marathi','Speaks Marathi',3,'False','ShortText',,),
(172,'Moldavian','Speaks Moldavian',3,'False','ShortText',,),
(173,'Mongolian','Speaks Mongolian',3,'False','ShortText',,),
(174,'Nauru','Speaks Nauru',3,'False','ShortText',,),
(175,'Nepali','Speaks Nepali',3,'False','ShortText',,),
(176,'Norwegian','Speaks Norwegian',3,'False','ShortText',,),
(177,'Occitan','Speaks Occitan',3,'False','ShortText',,),
(178,'Oriya','Speaks Oriya',3,'False','ShortText',,),
(179,'Oromo (Afaan Oromo)','Speaks Oromo (Afaan Oromo)',3,'False','ShortText',,),
(180,'Papiamentu','Speaks Papiamentu',3,'False','ShortText',,),
(181,'Pashto (Pushto)','Speaks Pashto (Pushto)',3,'False','ShortText',,),
(182,'Polish','Speaks Polish',3,'False','ShortText',,),
(183,'Portuguese','Speaks Portuguese',3,'False','ShortText',,),
(184,'Punjabi','Speaks Punjabi',3,'False','ShortText',,),
(185,'Quechua','Speaks Quechua',3,'False','ShortText',,),
(186,'Rhaeto-Romance','Speaks Rhaeto-Romance',3,'False','ShortText',,),
(187,'Romanian','Speaks Romanian',3,'False','ShortText',,),
(188,'Russian','Speaks Russian',3,'False','ShortText',,),
(189,'Sami (Lappish)','Speaks Sami (Lappish)',3,'False','ShortText',,),
(190,'Samoan','Speaks Samoan',3,'False','ShortText',,),
(191,'Sangro','Speaks Sangro',3,'False','ShortText',,),
(192,'Sanskrit','Speaks Sanskrit',3,'False','ShortText',,),
(193,'Serbian','Speaks Serbian',3,'False','ShortText',,),
(194,'Serbo-Croatian','Speaks Serbo-Croatian',3,'False','ShortText',,),
(195,'Sesotho','Speaks Sesotho',3,'False','ShortText',,),
(196,'Setswana','Speaks Setswana',3,'False','ShortText',,),
(197,'Shona','Speaks Shona',3,'False','ShortText',,),
(198,'Sichuan Yi','Speaks Sichuan Yi',3,'False','ShortText',,),
(199,'Sindhi','Speaks Sindhi',3,'False','ShortText',,),
(200,'Sinhalese','Speaks Sinhalese',3,'False','ShortText',,),
(201,'Siswati','Speaks Siswati',3,'False','ShortText',,),
(202,'Slovak','Speaks Slovak',3,'False','ShortText',,),
(203,'Slovenian','Speaks Slovenian',3,'False','ShortText',,),
(204,'Somali','Speaks Somali',3,'False','ShortText',,),
(205,'Spanish','Speaks Spanish',3,'False','ShortText',,),
(206,'Sundanese','Speaks Sundanese',3,'False','ShortText',,),
(207,'Swahili (Kiswahili)','Speaks Swahili (Kiswahili)',3,'False','ShortText',,),
(208,'Swedish','Speaks Swedish',3,'False','ShortText',,),
(209,'Syriac','Speaks Syriac',3,'False','ShortText',,),
(210,'Tagalog','Speaks Tagalog',3,'False','ShortText',,),
(211,'Tajik','Speaks Tajik',3,'False','ShortText',,),
(212,'Tamazight','Speaks Tamazight',3,'False','ShortText',,),
(213,'Tamil','Speaks Tamil',3,'False','ShortText',,),
(214,'Tatar','Speaks Tatar',3,'False','ShortText',,),
(215,'Telugu','Speaks Telugu',3,'False','ShortText',,),
(216,'Thai','Speaks Thai',3,'False','ShortText',,),
(217,'Tibetan','Speaks Tibetan',3,'False','ShortText',,),
(218,'Tigrinya','Speaks Tigrinya',3,'False','ShortText',,),
(219,'Tonga','Speaks Tonga',3,'False','ShortText',,),
(220,'Tsonga','Speaks Tsonga',3,'False','ShortText',,),
(221,'Turkish','Speaks Turkish',3,'False','ShortText',,),
(222,'Turkmen','Speaks Turkmen',3,'False','ShortText',,),
(223,'Twi','Speaks Twi',3,'False','ShortText',,),
(224,'Uighur','Speaks Uighur',3,'False','ShortText',,),
(225,'Ukrainian','Speaks Ukrainian',3,'False','ShortText',,),
(226,'Urdu','Speaks Urdu',3,'False','ShortText',,),
(227,'Uzbek','Speaks Uzbek',3,'False','ShortText',,),
(228,'Venda','Speaks Venda',3,'False','ShortText',,),
(229,'Vietnamese','Speaks Vietnamese',3,'False','ShortText',,),
(230,'Volapk','Speaks Volapk',3,'False','ShortText',,),
(231,'Wallon','Speaks Wallon',3,'False','ShortText',,),
(232,'Welsh','Speaks Welsh',3,'False','ShortText',,),
(233,'Wolof','Speaks Wolof',3,'False','ShortText',,),
(234,'Xhosa','Speaks Xhosa',3,'False','ShortText',,),
(235,'Yi','Speaks Yi',3,'False','ShortText',,),
(236,'Yiddish','Speaks Yiddish',3,'False','ShortText',,),
(237,'Yoruba','Speaks Yoruba',3,'False','ShortText',,),
(238,'Zulu','Speaks Zulu',3,'False','ShortText',,),
(242,'Application','Set of specific details related to a given application record.',45,'True','Related Set',,),
(244,'Submission Details','Application Submission',43,'True','Related Set',,),
(246,'Submission Date','Date application was submitted.',244,'True','Date',,),
(248,'HOH Enrolled','Head of Household enrolled in education program.',43,'True','Text',,),
(249,'Program Eligibility','Data indicating the eligibility of this application per program.',6,'True',,','),
(250,'Income','Gross Annual Income',43,'True','Related Set',,),
(251,'Pending','Outcome is currently pending.',35,'True',,','),
(252,'Criminal History','Legal details related to criminal history.',43,'True','Text',,),
(254,'Program Entrance','Entrance Offer Accepted - Moved In',1303,'True',,','),
(255,'Relation','Contact Relationship',8,'True','ShortText',,),
(256,'Health Details','Health related data collection.',43,'True','Related Set',,),
(257,'History of Substance Use','Chronic Substance Use',1302,'True','ShortText',,),
(258,'Debt Source (ID)','Utility Debt Sources',10,'True','Integer',,),
(259,'Amount Owed','Amount owed to utility company.',10,'True','Currency',,),
(260,'DV/sexual assault','History of Domestic Violence / Sexual Assault',1302,'True','ShortText',,),
(261,'Communicable Disease','Communicable disease.',1302,'True','ShortText',,),
(263,'Annual Income Amount','Amount of Income Recieved',250,'True','Currency',,),
(265,'Income Type','Identifys whether this record is employment income or non-employment income.',44,'True',,','),
(268,'Preferred Language','Applicants preferred Language',43,'True','List',,),
(269,'Interpreter','Applicant has interpreter',268,'True','YesNo',,),
(270,'Nonemployment Income','Income is received through non-employment.',298,'True','Currency',,),
(271,'Employment Income','Income received through employment.',298,'True','Currency',Currency','Employment Start Date'),
(272,'Child Support','Income received through child support source.',270,'True','Currency',,),
(273,'SSDI','Income received through disability benefits.',270,'True','Currency',,),
(274,'SSI','Income received through social security program.',270,'True','Currency',,),
(275,'TANF','Income received through TANF program.',270,'True','Currency',,),
(276,'Unemployment','Income recieved through unemployment benefits program.',270,'True','Currency',,),
(277,'External Participation','Applicant participation in programs outside this waitlist.',43,'True','List',,),
(278,'Success Project','Applicant is part of success project program.',1300,'True',,','),
(279,'Refugee Resettlement','Applicant participation in refugee resettlement program.',1300,'True','ShortText',,),
(280,'Application Name','Name used to identify this application',43,'True','ShortText',,),
(283,'Aunt Bertha','Application submitted through AuntBertha.com',1301,'False',,','),
(284,'Moved In','Moved In',254,'True','Date',,),
(285,'Exited Program','Exited Program',254,'True','ShortText',,),
(286,'Mission','This message is display at the top of your application program's mission',1310,'True',,','),
(288,'Moved Out','Particpant moved out of the property.',284,'True',,','),
(292,'Unit Key','Unit existing in this property.',33,'True',,','),
(293,'Unit Type','Bedroom / Bath Size',292,'True',,','),
(294,'Unit Number','Unit Number.',292,'True',,','),
(295,'Unit Address','Unit Address.',292,'True',,','),
(296,'Unit Building','Unit building number.',292,'True',,','),
(297,'Unit Sq Ft.','Square feet of this unit.',292,'True',,','),
(298,'Income Source','Source of this income detail.',250,'True','ShortText',,),
(300,'Data Type','List of data types.',1310,'True','ShortText',,),
(301,'YesNo','YesNo data type.',300,'True','YesNo',,),
(302,'Currency','Currency data type.',300,'True','Currency',,),
(303,'Date','Date data type.',300,'True','Date',,),
(304,'DateWithTime','DateWithTime data type.',300,'True','DateWithTime',,),
(305,'Float','Float data type.',300,'True','Float',,),
(306,'Integer','Integer data type.',300,'True','Integer',,),
(307,'LongText','LongText data type.',300,'True','LongText',,),
(308,'ShortText','ShortText data type.',300,'True','ShortText',,),
(309,'Text','Text data type.',300,'True','Text',,),
(310,'Time','Time data type.',300,'True','Time',,),
(1298,'Utility Company','List of local utility providers.',44,'False','ShortText',,),
(1299,'Utilities','System level details describe particulars of this specific waitlist details including what programs are available at what properties. Variables defining system level details are held in this container.',45,'True',,','),
(1300,'External Programs','External programs applicants may have participatory relationships with.',44,'False','ShortText',,),
(1301,'Submission Sources','Application submission sources beyond paper app.',44,'False','Related Set',,),
(1302,'Disability Type','Types of disabilities.',44,'True','ShortText',,'Date Recorded'),
(1303,'Possible Outcomes','Outcome options available in this system.',44,'True',,','),
(1304,'Content Type','Type of content related to a specific detail.',1310,'True',,','),
(1305,'Transaction','Examples of transactional content include meetings, appointments and purchases. Transactions are a type of structured content.',1304,'True','Transaction',,),
(1306,'Analysis','Examples of analytical content include client reports, outcome analyses and case management assessments.  Analyzed content is a form of unstructured content.',1304,'True','Analysis',,),
(1307,'Authored','Examples of authored content include text documents, presentations, emails, and case notes. Authored content is a type of unstructured content.',1304,'True','Authored',,),
(1308,'Publication','Examples of published content include websites, handbooks and forms. Published content is a type of unstructured content.',1304,'True','Publication',,),
(1309,'Aggregate','Aggregate data type.',300,'True','Aggregate',,),
(1310,'System Details','Define information related to this specific instance of the Waitlist system. System level details describe particulars including available programs and properties.',45,'True',,','),
(1312,'Calculation','Calculated field.',300,'True','ShortText',,),
(1313,'Paper App','Application submitted via handwritten paper application.',1301,'False','ShortText',,),
(1314,'SharePoint','Application is submitted via SharePoint interface.',1301,'False','ShortText',,),
(1315,'List','List of items',300,'True','Aggregate',,),
(1316,'Related Set','Set of related details create the components of this piece of information.',300,'True',,','),
(1317,'Parent','Parent or grandparent.',60,'False','ShortText',,),
(1318,'Income Frequency','Frequency income is received. Used to calculate gross income after user inputs initial amount.',44,'False','Integer',,),
(1319,'Once a Year (Annually)','True',1318,'True','Integer',,),
(1320,'Every Two Months',6,1318,'True','Integer',,),
(1321,'Every Month',12,1318,'True','Integer',,),
(1322,'Twice a Month',24,1318,'True','Integer',,),
(1323,'Every Two Weeks',26,1318,'True','Integer',,),
(1324,'Every Week',52,1318,'True','Integer',,),
(1325,'Twice a Week',104,1318,'True','Integer',,),
(1326,'Once a Day',365,1318,'True','Integer',,),
(1327,'Summary Details','Aggregated summary of application information.',242,'False','Related Set',,)
